// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace FailFast
{
    internal sealed partial class Vsix
    {
        public const string Id = "FailFast.897947cf-5417-419c-9d8e-450b9480b07d";
        public const string Name = "Fail Fast";
        public const string Description = @"Skips projects that depend on a failed project while continuing to build independent projects.";
        public const string Language = "en-US";
        public const string Version = "1.0.900";
        public const string Author = "Mads Kristensen";
        public const string Tags = "";
        public const bool IsPreview = false;
    }
}
