// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace FailFast
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string FailFastString = "35066804-bfb3-4363-9dff-807d8cfb29d6";
        public static Guid FailFast = new Guid(FailFastString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ToggleFailFastCommand = 0x0102;
    }
}
